[package]
name = "rpg-game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5" }
tokio = {version = "1.43.0", features = ["full"]}
once_cell = "1.20.3"
lazy_static = "1.5.0"
bevy = "0.15.2"